spring:
  mvc:
    view:

      prefix: /WEB-INF/views/
      suffix: .jsp
      #templates下面的页面必须配合thymeleaf使用 在pom.xml添加thymeleaf的依赖才能正常使用
      #prefix: /templates/
      #suffix: .html
  datasource:
    url: jdbc:mysql://localhost:3306/cyz?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
